#ifndef SEVENSEGMENT_H
#define SEVENSEGMENT_H

#define SEVENSEGMENT_MAX_CLIENTS    3

#define SEVENSEGMENT_CLEAR_SCREEN   0x76
#define SEVENSEGMENT_DECIMAL_CTRL   0x77
#define SEVENSEGMENT_BRIGHTNESS     0x7a
#define SEVENSEGMENT_DIGIT_1        0x7b
#define SEVENSEGMENT_DIGIT_2        0x7c
#define SEVENSEGMENT_DIGIT_3        0x7d
#define SEVENSEGMENT_DIGIT_4        0x7e
#define SEVENSEGMENT_FACTORY_RESET  0x81

enum SevenSegmentProcFile {
    SEVENSEGMENT_BRIGHTNESS_FILE,
    SEVENSEGMENT_CLEAR_FILE,
    SEVENSEGMENT_CUSTOM_DIGIT1_FILE,
    SEVENSEGMENT_CUSTOM_DIGIT2_FILE,
    SEVENSEGMENT_CUSTOM_DIGIT3_FILE,
    SEVENSEGMENT_CUSTOM_DIGIT4_FILE,
    SEVENSEGMENT_DECIMALS_FILE,
    SEVENSEGMENT_NAME_FILE,
    SEVENSEGMENT_TEXT_FILE,
    SEVENSEGMENT_UNKNOWN_FILE
};

#endif // SEVENSEGMENT_H
